"""
tests/test_operators_are_qt_free.py

The guardrail behind P1.12e-2's whole point: no operator module contains
Qt.

Before this item, ``operators/plot_advanced.py`` and
``operators/video_frames.py`` each built a ``QDialog`` by hand in
``get_parameters_dialog()``, and ``operators/base.py`` carried a
``QDialog`` example in a docstring. That put UI code in the analysis layer
and made those operators impossible to run from a plain script, a test, or
a future headless terminal. P1.12e-2 deleted ``get_parameters_dialog``
everywhere: MainWindow now builds the parameter form from each mode's
declared ``ParameterSpec`` entries (``ui/parameter_dialog.py``), so an
operator never touches Qt.

This test parses every module under ``operators/`` with ``ast`` -- not a
text search, which a comment or a docstring mentioning ``PySide6`` would
trip -- and asserts none of them imports the Qt binding, at module level
or inside a function. It also asserts the walk actually found modules, so
a broken glob cannot let the check pass by inspecting nothing.

``operators/descriptor.py`` states the same rule for itself in prose
("no Qt"); this test makes it enforceable for the whole package.

Run with:
    python -m pytest tests/test_operators_are_qt_free.py

# run-tests: combined -- names the Qt binding in a source-scan assertion but never imports it
"""

from __future__ import annotations

import ast
import pathlib

ROOT = pathlib.Path(__file__).parent.parent
OPERATORS_DIR = ROOT / "operators"

# Every distribution whose import means "this module pulls in a Qt
# binding". PySide6 is the one Gelem uses; the others are listed so a
# future switch to another binding is caught too.
_QT_DISTRIBUTIONS = ("PySide6", "PySide2", "PyQt5", "PyQt6", "shiboken6")


def _qt_imports_in_module(path: pathlib.Path) -> list[str]:
    """Return the Qt module names imported anywhere in one Python file.

    Walks the whole AST, so an import nested inside a method body (the way
    the deleted get_parameters_dialog() did its ``from PySide6.QtWidgets
    import ...``) is caught, not just module-level imports.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    hits: list[str] = []

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if _names_a_qt_binding(alias.name):
                    hits.append(alias.name)
        elif isinstance(node, ast.ImportFrom):
            # A relative import (node.module is None for `from . import x`)
            # cannot reach an external Qt binding, so only absolute
            # `from PySide6...` matters here.
            if node.module and _names_a_qt_binding(node.module):
                hits.append(node.module)

    return hits


def _names_a_qt_binding(module_name: str) -> bool:
    """True when a dotted module name is, or sits under, a Qt binding."""
    return any(
        module_name == dist or module_name.startswith(dist + ".")
        for dist in _QT_DISTRIBUTIONS
    )


def _operator_modules() -> list[pathlib.Path]:
    """Every *.py file directly under operators/."""
    return sorted(OPERATORS_DIR.glob("*.py"))


def test_the_walk_finds_operator_modules():
    # A guardrail that inspects nothing passes vacuously. Pin a floor that
    # is comfortably below today's count (14) so adding or removing one
    # operator does not make this test brittle, but an empty glob does
    # fail it.
    modules = _operator_modules()
    assert len(modules) >= 8, (
        f"expected to find several operator modules under {OPERATORS_DIR}, "
        f"found {len(modules)}: {[m.name for m in modules]}"
    )


def test_no_operator_module_imports_qt():
    violations: dict[str, list[str]] = {}
    for path in _operator_modules():
        hits = _qt_imports_in_module(path)
        if hits:
            violations[path.name] = hits

    assert not violations, (
        "operator modules import a Qt binding -- an operator must contain "
        "no Qt (parameter forms are generated by MainWindow from the "
        "declared ParameterSpec entries, ui/parameter_dialog.py):\n"
        + "\n".join(
            f"  {name}: {', '.join(mods)}" for name, mods in violations.items()
        )
    )
